---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu
    box: ubuntu/bionic64
    # instance_raw_config_args:
    #   - "vm.network 'forwarded_port', guest: 80, host: 8088"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        kibana_distr_type: local
        kibana_version: "7.11.1"
        kibana_url: "https://artifacts.kibana.co/downloads/kibana/kibana-7.11.1-linux-x86_64.tar.gz"
        kibana_distr_name: kibana-{{ kibana_version }}-linux-x86_64.tar.gz
        kibana_folder: "{{ kibana_distr_name.split('-')[:2] | join('-')  }}"
        kibana_home: "/opt/kibana/{{ kibana_folder }}"
        environ_type: "vagrant"
verifier:
  name: ansible

