---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check Kibana can running
    command:
      cmd: "kibana --version"
    environment:
      PATH: "$PATH:{{ kibana_home }}/bin"
      # PATH: "$PATH:/opt/kibana/kibana-7.11.1/bin"
    changed_when: false
